### ISSUE TITLE
Unable to expand an "executable" Spring Boot JAR

### ISSUE THREAD

**Issue by saturnism** [cloudfoundry/archive-expanding-cnb#2]
I built a JAR with JHipster and tried to deploy using buildpacks. It failed in the archive expanding buildpack:

```
build-step-build] Cloud Foundry Archive Expanding Buildpack 1.0.0-BUILD-SNAPSHOT
[build-step-build]     Expanding /workspace/demo-0.0.1-SNAPSHOT.jar to /workspace
[build-step-build] zip: not a valid zip file
[build-step-build] Error: failed to build: exit status 103
[build-step-build] Build Failed
```

JHipster creates `executable`JAR

pom.xml w/ Spring Boot Maven Plugin
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <mainClass>${start-class}</mainClass>
        <executable>true</executable>
        </configuration>
...
```
I can confirm w/ this flag set to `false`, the then it'll be unpacked without issues.

**Comment by nebhale** [comment]
Ah yes, the long-standing thing where making it executable means that nearly no tools that understand zip files can handle them.  Spring Boot even [warns against using the feature](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-install).  I don't believe that we'll aim to support these kinds of JAR files.

**Comment by saturnism** [comment]
Will notify JHipster.

Apparently it can be fixed using `zip -A thefile.jar` and then the file is still self-executable, as well as expandable by this.

**Comment by nebhale** [comment]
Beautifully cryptic help message

```
-A   adjust self-extracting exe
```

**Comment by saturnism** [comment]
i know ;) it does fix some offsets. I was trying to find out if there is something that Spring Boot plugin is doing that may have caused the offset differences.

**Comment by saturnism** [comment]
JHipster will set `executable` to `false` for future release. https://github.com/jhipster/generator-jhipster/issues/10255

**Comment by nebhale** [comment]
Sounds great.
